name: Http4s Tracer
baseurl: /http4s-tracer
description: End to end tracing system for Http4s
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0-M1
org: com.github.gvolpe
markdown: kramdown
