name: Http4s Tracer
baseurl: ''
description: End-to-end tracing system for Http4s
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.3.0
org: dev.profunktor
markdown: kramdown
