name: Http4s Tracer
baseurl: ''
description: End-to-end tracing system for Http4s
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.4.0-RC1
org: dev.profunktor
markdown: kramdown
