name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-java@v10

    - name: Cache Coursier dependencies
      uses: actions/cache@v1.2.0
      with:
       path: ~/.cache/coursier
       key: ${{ runner.os }}-${{ github.ref }}-coursier
       restore-keys: |
        ${{ runner.os }}-${{ github.ref }}-coursier

    - name: Cache Ivy dependencies
      uses: actions/cache@v1.2.0
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-${{ github.ref }}-ivy2
        restore-keys: |
         ${{ runner.os }}-${{ github.ref }}-ivy2

    - name: Build
      run: sbt -J-Xms2G -J-Xmx4G buildHttp4sTracer
